import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from '../components/Header'; // Header コンポーネントをインポート
import Footer from '../components/Footer'; // Footer コンポーネントをインポート

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <Header /> {/* Header コンポーネントをレンダリング */}
        <main className="flex-grow">
          {children}
        </main>
        <Footer /> {/* Footer コンポーネントをレンダリング */}
      </body>
    </html>
 );
}
